version: '3.8'
services:
  postgres:
    image: postgres:13.4-alpine
    volumes:
      - sensor-postgres-volume:/var/lib/postgresql/data
      - ./infra/db/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DBS: "sensor"
      POSTGRES_PASSWORD: "postgres"


volumes:
  sensor-postgres-volume: null
